<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Actualizar landing_styles con el nuevo esquema por bloques
        DB::table('site_settings')->where('key', 'landing_styles')->update([
            'value' => json_encode([
                'global' => [
                    'font_family_title'  => 'Inter',
                    'font_family_body'   => 'Inter',
                    'font_weight_title'  => '700',
                    'font_weight_body'   => '400',
                    'color_primary'      => '#22c55e',
                    'color_secondary'    => '#eab308',
                    'color_text'         => '#1e293b',
                    'color_title'        => '#0f172a',
                    'color_bg_page'      => '#f8faf6',
                    'font_size_h1'       => '2.75rem',
                    'font_size_h2'       => '2rem',
                    'font_size_h3'       => '1.5rem',
                    'font_size_body'     => '1rem',
                    'font_size_small'    => '0.875rem',
                    'line_height'        => '1.65',
                    'letter_spacing'     => '0em',
                ],
                'hero' => [
                    'font_family_title'    => 'Inter',
                    'font_weight_title'    => '900',
                    'text_transform_title' => 'none',
                    'text_align'           => 'left',
                    'font_size_title'      => '3.5rem',
                    'font_size_subtitle'   => '1.5rem',
                    'font_size_description'=> '1.125rem',
                    'letter_spacing_title' => '-0.02em',
                    'line_height_title'    => '1.1',
                    'color_title'          => '#ffffff',
                    'color_subtitle'       => '#eab308',
                    'color_description'    => '#cbd5e1',
                    'color_overlay'        => '#0f172a',
                    'overlay_opacity'      => '0.55',
                    'btn_primary_bg'       => '#22c55e',
                    'btn_primary_text'     => '#ffffff',
                    'btn_secondary_bg'     => 'transparent',
                    'btn_secondary_text'   => '#ffffff',
                    'btn_border_radius'    => '0.5rem',
                ],
                'nav' => [
                    'font_family'      => 'Inter',
                    'font_weight'      => '500',
                    'font_size'        => '0.9rem',
                    'text_transform'   => 'none',
                    'color_bg'         => '#0f172a',
                    'color_bg_scroll'  => '#1e293b',
                    'color_link'       => '#f1f5f9',
                    'color_link_hover' => '#22c55e',
                    'color_logo'       => '#ffffff',
                    'topbar_bg'        => '#166534',
                    'topbar_text'      => '#dcfce7',
                    'topbar_font_size' => '0.8rem',
                ],
                'section_title' => [
                    'font_family'       => 'Inter',
                    'font_weight'       => '800',
                    'font_size'         => '2rem',
                    'text_transform'    => 'none',
                    'text_align'        => 'center',
                    'color_title'       => '#0f172a',
                    'color_subtitle'    => '#64748b',
                    'color_badge'       => '#22c55e',
                    'color_badge_text'  => '#ffffff',
                    'margin_bottom'     => '3rem',
                    'font_size_subtitle'=> '1.1rem',
                    'letter_spacing'    => '0em',
                    'line_height'       => '1.3',
                ],
                'cards' => [
                    'font_family_title'  => 'Inter',
                    'font_weight_title'  => '700',
                    'font_size_title'    => '1.25rem',
                    'font_size_body'     => '0.95rem',
                    'color_bg'           => '#ffffff',
                    'color_bg_hover'     => '#f0fdf4',
                    'color_title'        => '#0f172a',
                    'color_body'         => '#64748b',
                    'color_icon'         => '#22c55e',
                    'color_border'       => '#e2e8f0',
                    'color_border_hover' => '#22c55e',
                    'border_radius'      => '1rem',
                    'padding'            => '1.5rem',
                ],
                'stats' => [
                    'font_family_value'  => 'Inter',
                    'font_weight_value'  => '800',
                    'font_size_value'    => '3rem',
                    'font_size_label'    => '0.9rem',
                    'color_bg'           => '#0f172a',
                    'color_value'        => '#22c55e',
                    'color_label'        => '#94a3b8',
                    'color_icon'         => '#eab308',
                ],
                'testimonials' => [
                    'font_family_quote'  => 'Inter',
                    'font_style_quote'   => 'italic',
                    'font_size_quote'    => '1.1rem',
                    'font_size_author'   => '0.95rem',
                    'color_bg_card'      => 'rgba(255,255,255,0.05)',
                    'color_quote_text'   => '#e2e8f0',
                    'color_author'       => '#94a3b8',
                    'color_stars'        => '#eab308',
                    'color_section_bg'   => '#0f172a',
                ],
                'footer' => [
                    'font_family'          => 'Inter',
                    'font_size_body'       => '0.9rem',
                    'font_size_title'      => '1rem',
                    'font_weight_title'    => '600',
                    'color_bg'             => '#020617',
                    'color_text'           => '#94a3b8',
                    'color_title'          => '#f1f5f9',
                    'color_link'           => '#94a3b8',
                    'color_link_hover'     => '#22c55e',
                    'color_border'         => '#1e293b',
                    'color_copyright_bg'   => '#000000',
                    'color_copyright_text' => '#475569',
                ],
                'buttons' => [
                    'font_family'              => 'Inter',
                    'font_weight'              => '600',
                    'font_size'                => '0.95rem',
                    'text_transform'           => 'none',
                    'primary_bg'               => '#22c55e',
                    'primary_text'             => '#ffffff',
                    'primary_bg_hover'         => '#16a34a',
                    'primary_border_radius'    => '0.5rem',
                    'primary_padding'          => '0.75rem 1.75rem',
                    'secondary_bg'             => 'transparent',
                    'secondary_text'           => '#22c55e',
                    'secondary_border'         => '#22c55e',
                    'secondary_bg_hover'       => '#f0fdf4',
                    'secondary_border_radius'  => '0.5rem',
                ],
            ]),
            'updated_at' => now(),
        ]);

        // Actualizar ecommerce_styles con el nuevo esquema por bloques
        DB::table('site_settings')->where('key', 'ecommerce_styles')->update([
            'value' => json_encode([
                'global' => [
                    'font_family_title'  => 'Inter',
                    'font_family_body'   => 'Inter',
                    'font_weight_title'  => '700',
                    'font_weight_body'   => '400',
                    'color_primary'      => '#22c55e',
                    'color_accent'       => '#eab308',
                    'color_text'         => '#1e293b',
                    'color_title'        => '#0f172a',
                    'color_bg_page'      => '#f8faf6',
                    'font_size_h1'       => '2.25rem',
                    'font_size_h2'       => '1.75rem',
                    'font_size_h3'       => '1.25rem',
                    'font_size_body'     => '0.95rem',
                    'line_height'        => '1.5',
                ],
                'store_hero' => [
                    'font_family_title'  => 'Inter',
                    'font_weight_title'  => '800',
                    'font_size_title'    => '2.75rem',
                    'text_align'         => 'center',
                    'color_bg'           => '#0f172a',
                    'color_title'        => '#ffffff',
                    'color_subtitle'     => '#eab308',
                    'color_badge_bg'     => '#22c55e',
                    'color_badge_text'   => '#ffffff',
                ],
                'product_card' => [
                    'font_family_name'    => 'Inter',
                    'font_weight_name'    => '600',
                    'font_size_name'      => '1rem',
                    'font_size_price'     => '1.25rem',
                    'font_size_description' => '0.875rem',
                    'color_bg'            => '#ffffff',
                    'color_bg_hover'      => '#f0fdf4',
                    'color_name'          => '#0f172a',
                    'color_price'         => '#16a34a',
                    'color_price_credit'  => '#eab308',
                    'color_description'   => '#64748b',
                    'color_border'        => '#e2e8f0',
                    'color_badge_stock'   => '#dcfce7',
                    'border_radius'       => '1rem',
                    'btn_bg'              => '#22c55e',
                    'btn_text'            => '#ffffff',
                    'btn_bg_hover'        => '#16a34a',
                    'btn_font_size'       => '0.875rem',
                    'btn_font_weight'     => '600',
                ],
                'product_detail' => [
                    'font_family_title'    => 'Inter',
                    'font_weight_title'    => '700',
                    'font_size_title'      => '1.875rem',
                    'font_size_price'      => '1.75rem',
                    'color_title'          => '#0f172a',
                    'color_price'          => '#16a34a',
                    'color_price_credit'   => '#d97706',
                    'color_bg'             => '#f8faf6',
                    'color_description'    => '#475569',
                ],
                'filters' => [
                    'font_family'          => 'Inter',
                    'font_size'            => '0.875rem',
                    'font_weight_active'   => '700',
                    'color_bg_active'      => '#22c55e',
                    'color_text_active'    => '#ffffff',
                    'color_bg_inactive'    => '#f1f5f9',
                    'color_text_inactive'  => '#64748b',
                    'color_border'         => '#e2e8f0',
                ],
                'checkout' => [
                    'font_family'              => 'Inter',
                    'font_size_title'          => '1.25rem',
                    'font_size_item'           => '0.95rem',
                    'color_bg_panel'           => '#ffffff',
                    'color_total'              => '#0f172a',
                    'color_btn_checkout_bg'    => '#22c55e',
                    'color_btn_checkout_text'  => '#ffffff',
                ],
            ]),
            'updated_at' => now(),
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::table('site_settings')->whereIn('key', ['landing_styles', 'ecommerce_styles'])->delete();
    }
};
